### ISSUE TITLE
Why save secrets in /run?

### ISSUE THREAD

**Issue by Gerschtli** [jordanisaacs/homeage#12]
Hey, maybe a stupid question but why are the secrets saved to `/run/user/$UID/secrets` per defaullt? If they would be saved in the home directory like `${XDG_DATA_DIR:-~/.local/share}/secrets` there would be no need of systemd services because the secrets will remain there after reboots..

**Comment by jordanisaacs** [comment]
This my understanding. `/run` is a tmpfs. That means it is stored in ram (but uses swap). This means that secrets aren't loaded onto disk unless you have swap enabled.

The ideal way is to mount it to a ramfs which is similar to tmpfs except that it doesn't use swap. So secrets will never be loaded to disk. However a ramfs needs to be mounted by sudo (not on by default). So I can't do that with home manager.

When I get around to separating service and activation options I am gonna look at a better way of declaring secrets. Prelim thoughts are a `homeage."secret".service.<file submodule>` and a `homeage."secret".activation.<file submodule>` with a `homeage.mountPath.service` and a `homeage.mountPath.activation` option.
