### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by shanesveller** [jordanisaacs/homeage#20]
Unfortunately, the change in #4 prevented users on MacOS from using this tool on those machines going forward, as we do not have access to systemd or a useful-parity replacement, even with `nix-darwin` in play. Can you recommend any compatible alternatives that are not systemd-based, and/or would you be interested in including that support here?

**Comment by Gerschtli** [comment]
I think the activation script approach would fit your use case the most (see #7 and #13).

**Comment by jordanisaacs** [comment]
It should now work on MacOS with the "activation" installation option set.
