### ISSUE TITLE
Fails to decrypt using `rage`

### ISSUE THREAD

**Issue by gvolpe** [jordanisaacs/homeage#28]
Giving `homeage` a try, I noticed the decryption command fails when using `rage` and only succeeds when using `age`. So basically setting `homeage.isRage = true;` would always fail, at least when having one or more symlinks.

I looked into the script and I don't see much wrong with the command, perhaps you get an idea?

Here's the log: 

```shell
× github-notifications-token-secret.service - Decrypt github-notifications-token secret
     Loaded: loaded (/home/gvolpe/.config/systemd/user/github-notifications-token-secret.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-09-09 14:34:03 CEST; 1min 38s ago
    Process: 1122308 ExecStart=/nix/store/v6cbpfzxixvsp63wdw6pkk1rgcn1cx4z-github-notifications-token-decrypt (code=exited, status=127)
   Main PID: 1122308 (code=exited, status=127)
        CPU: 6ms

Sep 09 14:34:03 tongfang-amd systemd[1937]: Starting Decrypt github-notifications-token secret...
Sep 09 14:34:03 tongfang-amd v6cbpfzxixvsp63wdw6pkk1rgcn1cx4z-github-notifications-token-decrypt[1122308]: Decrypting secret /nix/store/5v64cvw535zd3rvcks0q1r561xcbzwin-github.age to /run/user/1000/secrets/github-notifications-token
Sep 09 14:34:03 tongfang-amd systemd[1937]: github-notifications-token-secret.service: Main process exited, code=exited, status=127/n/a
Sep 09 14:34:03 tongfang-amd systemd[1937]: github-notifications-token-secret.service: Failed with result 'exit-code'.
Sep 09 14:34:03 tongfang-amd systemd[1937]: Failed to start Decrypt github-notifications-token secret.
```

**Comment by jordanisaacs** [comment]
Did you also change the package to rage, `homeage.pkg`? `isRage` doesn't change the package being used. Because rage is `/bin/rage` vs. `/bin/age` I needed a way for an end user to tell the script which path to use. 

I don't link this implementation but not sure of a better way to do it currently.

**Comment by gvolpe** [comment]
Now I see what that means 🤦🏽‍♂️ , thank you. Adding `homeage.pkg = pkgs.rage;` solves the issue.

**Comment by jordanisaacs** [comment]
No problem, looked at the option description and it could definitely be more clear.

**Comment by gvolpe** [comment]
@jordanisaacs the `isRage` option can be removed for the user (only left internally) with the following code, so we can rely solely on the package set. Happy to submit a PR if you agree.

```nix
{
  ageBin =
    let binName = (builtins.parseDrvName cfg.pkg.name).name;
    in ${cfg.pkg}/bin/${binName}";
}
```

**Comment by jordanisaacs** [comment]
I like it, nice solution. Thanks! feel free to submit a PR and I'll merge it.
