### ISSUE TITLE
Activation script reintroduction (support non-systemd systems)

### ISSUE THREAD

**Issue by jordanisaacs** [jordanisaacs/homeage#7]
Add option to use script instead of systemd for startup secret decryption.

Waiting on v0.1 stabilization of option set and writing checks/cleanup.

**Comment by Gerschtli** [comment]
This would also add support for other linux distros where no systemd is available, e.g. Windows WSL.

**Comment by jordanisaacs** [comment]
Currently available on main branch, will be released with v0.1
